version: "3.7"

services:
  web:
    image: ghcr.io/ibz/usocial:v0.1.5-buster@sha256:1b1215d7fba847bf922a2615fee6400ce61cac4545dff6bfcf9703af8e05b953
    restart: on-failure
    stop_grace_period: 1m
    ports:
      - ${APP_USOCIAL_PORT}:5000
    volumes:
      - ${LND_DATA_DIR}:/lnd:ro
      - ${APP_DATA_DIR}/data:/instance
    environment:
        USOCIAL_JOB: "WEB"
        APP_PASSWORD: "${APP_PASSWORD}"
        LND_IP: "${LND_IP}"
        LND_GRPC_PORT: ${LND_GRPC_PORT}
        LND_DIR: "/lnd"
    networks:
      default:
          ipv4_address: $APP_USOCIAL_IP
  fetcher:
    depends_on:
      - web
    image: ghcr.io/ibz/usocial:v0.1.5-buster@sha256:1b1215d7fba847bf922a2615fee6400ce61cac4545dff6bfcf9703af8e05b953
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/data:/instance
    environment:
        USOCIAL_JOB: "FETCH_FEEDS"
    networks:
      default:
          ipv4_address: $APP_USOCIAL_FETCHER_IP
