version: "3.7"

services:
  web:
    image: getumbrel/element-web:v1.7.34
    # NGINX parent container requires root
    # user: "1000:1000"
    restart: on-failure
    stop_grace_period: 1m
    ports:
      - "$APP_ELEMENT_PORT:80"
    networks:
      default:
        ipv4_address: $APP_ELEMENT_IP
