version: "3.7"

services:
  web:
    image: urbit-btc-node:latest
    restart: on-failure
    stop_grace_period: 1m
    ports:
      - 55555:50002
      - 9091:9090
    environment:
      ELECTRUM_IP: $ELECTRUM_IP
      ELECTRUM_PORT: $ELECTRUM_PORT
      BITCOIN_IP: $BITCOIN_IP
      BITCOIN_RPC_PORT: $BITCOIN_RPC_PORT
      BITCOIN_RPC_USER: $BITCOIN_RPC_USER
      BITCOIN_RPC_PASS: $BITCOIN_RPC_PASS
      BITCOIN_RPC_AUTH: $BITCOIN_RPC_AUTH
    extra_hosts:
        - "host.docker.internal:host-gateway"
