# Warning: it's not recommended to modify these files directly. Any
# modifications you make can break the functionality of your umbrel. These files
# are automatically reset with every Umbrel update.

verbose = 2
network = "bitcoin"
db_dir = "/data/db"
daemon_rpc_addr = "<bitcoin-ip>:<port>"
electrum_rpc_addr = "0.0.0.0:<electrum-port>"
server_banner = "Umbrel v<version>"
