version: "3.7"

services:
  backend:
    image: kolliderhq/kollider-lite-backend:v1.0.1@sha256:e095cd6209751277a1842ce4fa9e8de3a067963b9478441e890158c56161c2c3
    init: true
    user: 1000:1000
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${LND_DATA_DIR}:/lnd:ro
      - ${APP_DATA_DIR}/data/logs:/app/logs
    environment:
      LND_IP: $LND_IP
    networks:
      default:
        ipv4_address: $APP_KOLLIDER_HH_IP
  ws:
    image: kolliderhq/kollider-ws-client:v1.0.1@sha256:f365931a4ddb3aeb39ad545967eb175a155d35f8df125aa04ce93fd8405f68d4
    init: true
    user: 1000:1000
    restart: on-failure
    stop_grace_period: 1m
    ports:
      - "$APP_KOLLIDER_WS_PORT:8080"
    environment:
      APP_PASSWORD: $APP_PASSWORD
      KOLLIDER_ZMQ_ADDRESS: "tcp://${APP_KOLLIDER_HH_IP}:5556"
      KOLLIDER_ZMQ_SUB_ADDRESS: "tcp://${APP_KOLLIDER_HH_IP}:5557"
      KOLLIDER_ZMQ_HEDGER_ADDRESS: "tcp://${APP_KOLLIDER_HH_IP}:5558"
      KOLLIDER_ZMQ_HEDGER_SUB_ADDRESS: "tcp://${APP_KOLLIDER_HH_IP}:5559"
    networks:
      default:
        ipv4_address: $APP_KOLLIDER_WS_IP
  web:
    image: kolliderhq/kollider-lite-app:v1.0.1@sha256:704f6beb8c53e58180368372b483543d7a3fd115977a6028acab605a73af0d10
    init: true
    user: 1000:1000
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/data/cache/images:/app/.next/cache/images
    ports:
      - "$APP_KOLLIDER_PORT:3000"
    networks:
      default:
        ipv4_address: $APP_KOLLIDER_IP
